name: Deploy Windows Microservice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore Dependencies
        run: dotnet restore src/Microservice.sln

      - name: Build
        run: dotnet build src/Microservice.sln --configuration Release

      - name: Publish
        run: dotnet publish src/Microservice/Microservice.csproj -c Release -o ./publish

      - name: Zip the Windows Microservice
        run: | 
          powershell Compress-Archive -Path ./publish/* -DestinationPath ./windows-microservice.zip

      - name: Upload ZIP to S3
        run: |
          aws s3 cp ./windows-microservice.zip s3://alok-swimlaneartifacts/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
